// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:42ed701e3745f7c0b6edd8102fdba17f8d6ec9d37829c85f704d15114b53e54b
fn main() {
    let crate_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    cbindgen::generate(crate_dir)
        .expect("Unable to generate C bindings")
        .write_to_file("include/kreuzberg.h");

    let go_include_dir = std::path::Path::new("../../../packages/go/v5/include");
    std::fs::create_dir_all(go_include_dir).expect("Unable to create Go include directory");
    std::fs::copy("include/kreuzberg.h", go_include_dir.join("kreuzberg.h"))
        .expect("Unable to copy header to Go include directory");
}
