# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:12b84b5181353e57cf8816abc2de29663e9236e9727e5b0a2748a0da1e6cfe00
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: code
defmodule E2e.CodeTest do
  use ExUnit.Case, async: false

  describe "code_shebang_detection" do
    test "code_shebang_detection" do
      {:ok, result} = Kreuzberg.extract_file_sync("../../test_documents/code/script.sh", mime_type: "text/x-source-code")
      assert String.trim(result.mime_type) == "text/x-source-code"
      assert String.length(result.content) >= 10
      assert String.contains?(to_string(result.content), "build")
      assert String.contains?(to_string(result.content), "clean")
    end
  end
end
