# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e4016411e7334788f7340db4fb55dfcbdb99a6caacc28ba861e57988c290ac5d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: embed_extra
defmodule E2e.EmbedExtraTest do
  use ExUnit.Case, async: false

  describe "embed_texts_batch" do
    test "embed_texts_batch" do
      {:ok, result} = Kreuzberg.embed_texts(["Hello", "World"], config: "{}")
    end
  end
end
