// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9bc63954ac9bdd65fee2a491c84d9aa6503d9a8c5f52af31559f8ca5f8efe741
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Kreuzberg;
using static Kreuzberg.KreuzbergLib;

namespace Kreuzberg
{
    /// <summary>E2e tests for category: validator_management.</summary>
    public class ValidatorManagementTests
    {
            private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

        [Fact]
        public void Test_ValidatorsClear()
        {
            // Clear all validators and verify list is empty
            KreuzbergLib.ClearValidators();
        }

        [Fact]
        public void Test_ValidatorsList()
        {
            // List all registered validators
            var result = KreuzbergLib.ListValidators();

        }


    }
}
