// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e6212eb6fa81906428dec3a4f6f76ba51299d637e92ee852d0861e23fee94d53
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
//! E2e tests for category: embedding_backend_management

use kreuzberg::{clear_embedding_backends, list_embedding_backends};

#[test]
fn test_embedding_backends_clear() {
    // Clear all embedding backends and verify list is empty
    let _ = clear_embedding_backends();
}

#[test]
fn test_embedding_backends_list() {
    // List all registered embedding backends
    let _ = list_embedding_backends();
}
