// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3921494754999348bf3d40395755fdeadcc12e790553f6a1e97cbf0f0b48aab5
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
//! E2e tests for category: ocr_backend_management

use kreuzberg::{clear_ocr_backends, list_ocr_backends};

#[test]
fn test_ocr_backends_clear() {
    // Clear all OCR backends and verify list is empty
    let _ = clear_ocr_backends();
}

#[test]
fn test_ocr_backends_list() {
    // List all registered OCR backends
    let _ = list_ocr_backends();
}
