// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:798c535c3f9ef47d0997939e7703ee0e53148c21012209d2f2887a9d2c398dfb
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
//! E2e tests for category: post_processor_management

use kreuzberg::{clear_post_processors, list_post_processors};

#[test]
fn test_post_processors_clear() {
    // Clear all post-processors and verify list is empty
    let _ = clear_post_processors();
}

#[test]
fn test_post_processors_list() {
    // List all registered post-processors
    let _ = list_post_processors();
}
