<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:12a424777b6dfd42f15deb0e3e4fe4a28c232571127b0c84f03a61211e13aded
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef


declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg;use Kreuzberg\ExtractionConfig;
/** E2e tests for category: code. */
final class CodeTest extends TestCase
{

    /** Test language detection from shebang line via bytes input */
    public function test_code_shebang_detection(): void
    {        $result = Kreuzberg::extractFileSync("code/script.sh", "text/x-source-code", ExtractionConfig::from_json('{}'));

            $this->assertEquals("text/x-source-code", trim($result->mimeType));
            $this->assertGreaterThanOrEqual(10, strlen($result->getContent()));
            $this->assertStringContainsString("build", $result->getContent());
    $this->assertStringContainsString("clean", $result->getContent());

    }

}
