<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0a2d6533d94fafabee411df2ffae30ab22535f159fe8635814065d9693a96d57
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef


declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg;use Kreuzberg\EmbeddingConfig;
/** E2e tests for category: embed_extra. */
final class EmbedExtraTest extends TestCase
{

    /** Batch embed texts */
    public function test_embed_texts_batch(): void
    {        $config = EmbeddingConfig::from_json('{}');
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::embedTexts(["Hello", "World"], $config);


    }

}
