<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:891e1d77bb023040e6104fa1b8fc73d0cd76313f6884426cf131ca388b75c91b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef


declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg;use Kreuzberg\EmbeddingConfig;
/** E2e tests for category: embed_async_pending. */
final class EmbedAsyncPendingTest extends TestCase
{

    /** embed_texts_async: empty text list */
    public function test_embed_texts_async_empty_input(): void
    {        $result = Kreuzberg::embedTextsAsync([], ExtractionConfig::from_json('{}'));

        $this->assertCount(0, $result);
    }


    /** embed_texts_async: basic async embedding */
    public function test_embed_texts_async_happy(): void
    {        $result = Kreuzberg::embedTextsAsync(["First", "Second"], ExtractionConfig::from_json('{}'));

        $this->assertGreaterThanOrEqual(2, count($result));
    }


    /** embed_texts_async: preset override */
    public function test_embed_texts_async_preset_switch(): void
    {        $config = EmbeddingConfig::from_json(json_encode(["embeddingModel" => "default"]));
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::embedTextsAsync(["Text"], $config);


    }

}
