<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:da8dd0cc4572b882d883bcfd8d27a1c254e7c8b515af3d4084ed4d5d0af13acb
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef


declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg;use Kreuzberg\ExtractionConfig;
/** E2e tests for category: renderer_management. */
final class RendererManagementTest extends TestCase
{

    /** Clear all renderers and verify list is empty */
    public function test_renderers_clear(): void
    {        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::clearRenderers();


    }


    /** List all registered renderers */
    public function test_renderers_list(): void
    {        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::listRenderers();


    }

}
