<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9d60313b40f9983fe81d275bc7055967b7b8b0cdda04c68df16ef3d4fb383f58
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef


declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg;use Kreuzberg\ExtractionConfig;
/** E2e tests for category: validator_management. */
final class ValidatorManagementTest extends TestCase
{

    /** Clear all validators and verify list is empty */
    public function test_validators_clear(): void
    {        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::clearValidators();


    }


    /** List all registered validators */
    public function test_validators_list(): void
    {        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::listValidators();


    }

}
