// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f406519a6edc4c9afdcd4ac5b35a46f169dc35bcd2a665e0fe566f6395bf0d4c
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
// swift-format-ignore-file

import XCTest
import Foundation
import Kreuzberg
import RustBridge

/// E2e tests for category: document_extractor_management.
final class DocumentExtractorManagementTests: XCTestCase {
    func testDocumentExtractorsClear() throws {
        // Clear all document extractors and verify list is empty
        let result = try Kreuzberg.clearDocumentExtractors()
    }

    func testExtractorsList() throws {
        // List all registered document extractors
        let result = try Kreuzberg.listDocumentExtractors()
    }

}
