// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:fe45ffb7f9b7512de643a033269302032f9c39b4e890d181a16272b8ff2f4883
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
// swift-format-ignore-file

import XCTest
import Foundation
import Kreuzberg
import RustBridge

/// E2e tests for category: embed_extra.
final class EmbedExtraTests: XCTestCase {
    func testEmbedTextsBatch() throws {
        // Batch embed texts
        let configObj = try extractionConfigFromJson("{}")
        let result = try Kreuzberg.embedTexts(texts: ["Hello", "World"], config: configObj)
    }

}
