// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f52600d752fb709bbf53b92f06a8dc0dffe346fd6b25a46aa9aeb93c90c659fb
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
// swift-format-ignore-file

import XCTest
import Foundation
import Kreuzberg
import RustBridge

/// E2e tests for category: embeddings.
final class EmbeddingsTests: XCTestCase {
    func testEmbedTextsDifferentPreset() throws {
        // embed_texts: multilingual preset
        let configObj = try extractionConfigFromJson("{\"model\":{\"name\":\"multilingual\",\"type\":\"preset\"}}")
        let result = try Kreuzberg.embedTexts(texts: ["Hello world", "Test"], config: configObj)
        XCTAssertGreaterThanOrEqual(result.embeddings().count, 2)
    }

    func testGetEmbeddingPresetKnown() throws {
        // get_embedding_preset: known preset
        let result = try Kreuzberg.getEmbeddingPreset(name: "balanced")
    }

    func testGetEmbeddingPresetNominal() throws {
        // get_embedding_preset: nominal case
        let result = try Kreuzberg.getEmbeddingPreset(name: "balanced")
    }

    func testGetEmbeddingPresetUnknown() throws {
        // get_embedding_preset: unknown preset fails
        let result = try Kreuzberg.getEmbeddingPreset(name: "nonexistent-xyz")
        XCTAssertNil(result, "expected nil value")
    }

    func testListEmbeddingPresetsSanity() throws {
        // list_embedding_presets: returns at least one
        let result = try Kreuzberg.listEmbeddingPresets()
        XCTAssertFalse(result.isEmpty, "expected non-empty value")
    }

}
