// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9fdceb7521d6c56827334203f2281b74cfd2d54fa1ef94767bcd6d8de4581e54
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
// swift-format-ignore-file

import XCTest
import Foundation
import Kreuzberg
import RustBridge

/// E2e tests for category: ocr_backend_management.
final class OcrBackendManagementTests: XCTestCase {
    func testOcrBackendsClear() throws {
        // Clear all OCR backends and verify list is empty
        let result = try Kreuzberg.clearOcrBackends()
    }

    func testOcrBackendsList() throws {
        // List all registered OCR backends
        let result = try Kreuzberg.listOcrBackends()
    }

}
