// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:12983590d39acfabc06557c92d35e88a80de18c27b52706cdb3b9ee4ac3f537d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
// swift-format-ignore-file

import XCTest
import Foundation
import Kreuzberg
import RustBridge

/// E2e tests for category: registry_operations.
final class RegistryOperationsTests: XCTestCase {
    func testExtensionsDocx() throws {
        // Get file extensions for DOCX MIME type
        let result = try Kreuzberg.getExtensionsForMime(mime_type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document")
    }

    func testExtensionsHtml() throws {
        // Get file extensions for HTML MIME type
        let result = try Kreuzberg.getExtensionsForMime(mime_type: "text/html")
    }

    func testExtensionsPdf() throws {
        // Get file extensions for PDF MIME type
        let result = try Kreuzberg.getExtensionsForMime(mime_type: "application/pdf")
        XCTAssertTrue(result.map { $0.asStr().toString() }.contains("pdf"), "expected to contain: \("pdf")")
    }

}
