// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0e592ad148c1c4e544bb490b5d0ea7386bf5edbea1cc9db30d6d2af08449848a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
// swift-format-ignore-file

import XCTest
import Foundation
import Kreuzberg
import RustBridge

/// E2e tests for category: renderer_management.
final class RendererManagementTests: XCTestCase {
    func testRenderersClear() throws {
        // Clear all renderers and verify list is empty
        let result = try Kreuzberg.clearRenderers()
    }

    func testRenderersList() throws {
        // List all registered renderers
        let result = try Kreuzberg.listRenderers()
    }

}
