// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e0c9e7a788a3ed82f2baabaa2fcfb981c1e8b933c3c8a3fde5a8c1413b9e0c72
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
// swift-format-ignore-file

import XCTest
import Foundation
import Kreuzberg
import RustBridge

/// E2e tests for category: validator_management.
final class ValidatorManagementTests: XCTestCase {
    func testValidatorsClear() throws {
        // Clear all validators and verify list is empty
        let result = try Kreuzberg.clearValidators()
    }

    func testValidatorsList() throws {
        // List all registered validators
        let result = try Kreuzberg.listValidators()
    }

}
