// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:3113641b1269e339194df5687e5195067976b2f66fcdfe245780ad2c3b91bb9e
#nullable enable

using System;

namespace Kreuzberg;

public class CacheException : KreuzbergErrorException
{
    public CacheException(string message) : base(message) { }

    public CacheException(string message, Exception innerException) : base(message, innerException) { }
}
