// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:8c48f9948a52144d6ec35559da47b8e638623454fd1b57e761fe91896521e3ab
#nullable enable

using System;

namespace Kreuzberg;

public class CancelledException : KreuzbergErrorException
{
    public CancelledException(string message) : base(message) { }

    public CancelledException(string message, Exception innerException) : base(message, innerException) { }
}
