// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:c06496ee7ca6284b6328bdbfa35c507cb4c6c07c2c8ebff649257c54dffa2f9b
#nullable enable

using System;

namespace Kreuzberg;

public class EmbeddingException : KreuzbergErrorException
{
    public EmbeddingException(string message) : base(message) { }

    public EmbeddingException(string message, Exception innerException) : base(message, innerException) { }
}
