// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5d8ea8e4f5d1cf6f2b5f51d515b6abb18774abdfbe18fee7d61b5d8c7c4c89f8
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// A single heading in the hierarchy.
/// </summary>
public sealed record HeadingLevel
{
    /// <summary>
    /// Heading depth (1 = h1, 2 = h2, etc.)
    /// </summary>
    [JsonPropertyName("level")]
    public byte Level { get; init; } = 0;

    /// <summary>
    /// The text content of the heading.
    /// </summary>
    [JsonPropertyName("text")]
    public required string Text { get; init; }


    /// <summary>
    /// Parse a <see cref="HeadingLevel"/> from a JSON string.
    /// </summary>
    /// <exception cref="KreuzbergException">When the JSON cannot be deserialised.</exception>
    public static HeadingLevel FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<HeadingLevel>(json, JsonOptions)
                ?? throw new KreuzbergException($"Failed to parse HeadingLevel from JSON: deserializer returned null");
        }
        catch (KreuzbergException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new KreuzbergException($"Failed to parse HeadingLevel from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };

    /// <summary>Options for serializing config/input objects to FFI. Strips nulls
    /// (nullable C# fields default to null and would override required Rust fields with
    /// non-deserialisable nulls) but preserves explicit false/0 so caller intent is kept.</summary>
    private static readonly JsonSerializerOptions JsonSerializationOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
