// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:8e79f4058625e57bc6f727f2637185ca9551a9bdebf4ae3814e0c407db01fd45
#nullable enable

using System;

namespace Kreuzberg;

public class ImageProcessingException : KreuzbergErrorException
{
    public ImageProcessingException(string message) : base(message) { }

    public ImageProcessingException(string message, Exception innerException) : base(message, innerException) { }
}
