// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:8eb00fd65976c59360363aef0b443ab7bad45c050e258758843e9079d6d95183
#nullable enable

using System;

namespace Kreuzberg;

public class IoException : KreuzbergErrorException
{
    public IoException(string message) : base(message) { }

    public IoException(string message, Exception innerException) : base(message, innerException) { }
}
