// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:8a572a5e4a3561803d063e386976361a943ed3c26884e3ef3b77ac2008e5053b
#nullable enable

using System;

namespace Kreuzberg;

/// <summary>
/// Main error type for all Kreuzberg operations.
///
/// All errors in Kreuzberg use this enum, which preserves error chains
/// and provides context for debugging.
///
/// # Variants
///
/// - `Io` - File system and I/O errors (always bubble up)
/// - `Parsing` - Document parsing errors (corrupt files, unsupported features)
/// - `Ocr` - OCR processing errors
/// - `Validation` - Input validation errors (invalid paths, config, parameters)
/// - `Cache` - Cache operation errors (non-fatal, can be ignored)
/// - `ImageProcessing` - Image manipulation errors
/// - `Serialization` - JSON/MessagePack serialization errors
/// - `MissingDependency` - Missing optional dependencies (tesseract, etc.)
/// - `Plugin` - Plugin-specific errors
/// - `LockPoisoned` - Mutex/RwLock poisoning (should not happen in normal operation)
/// - `UnsupportedFormat` - Unsupported MIME type or file format
/// - `Other` - Catch-all for uncommon errors
/// </summary>
public class KreuzbergErrorException : KreuzbergException
{
    public KreuzbergErrorException(string message) : base(message) { }

    public KreuzbergErrorException(string message, Exception innerException) : base(message, innerException) { }
}
