// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:683b0dd949b2ec7735006cfaa9e49ef1ec496d0fa7dfaf70388be47c6f9903ca
#nullable enable

using System;

namespace Kreuzberg;

public class KreuzbergException : Exception
{
    public int Code { get; }

    public KreuzbergException(int code, string message) : base(message)
    {
        Code = code;
    }

    public KreuzbergException(string message) : base(message)
    {
        Code = 0;
    }

    public KreuzbergException(string message, Exception innerException) : base(message, innerException)
    {
        Code = 0;
    }
}
