// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:12b7635fda8dcfa1a4bbd159d0de1dff1e2d1c5e0bca631c335b069b5a4434fd
#nullable enable

using System;

namespace Kreuzberg;

public class LockPoisonedException : KreuzbergErrorException
{
    public LockPoisonedException(string message) : base(message) { }

    public LockPoisonedException(string message, Exception innerException) : base(message, innerException) { }
}
