// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:441ea53659e98c0dca7da1b9890af8ca3e35eb75829aa91b8405b95eb67da0f6
#nullable enable

using System;

namespace Kreuzberg;

public class MissingDependencyException : KreuzbergErrorException
{
    public MissingDependencyException(string message) : base(message) { }

    public MissingDependencyException(string message, Exception innerException) : base(message, innerException) { }
}
