// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:82113da94d6f34e24115a9860977891b97bbbdd33acf4c53c7119b0c4d1f77cf
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>
/// OCR backend types.
/// </summary>
[JsonConverter(typeof(OcrBackendTypeJsonConverter))]
public enum OcrBackendType
{
    /// <summary>
    /// Tesseract OCR (native Rust binding)
    /// </summary>
    [JsonPropertyName("tesseract")]
    Tesseract,
    /// <summary>
    /// EasyOCR (Python-based, via FFI)
    /// </summary>
    [JsonPropertyName("easyocr")]
    EasyOcr,
    /// <summary>
    /// PaddleOCR (Python-based, via FFI)
    /// </summary>
    [JsonPropertyName("paddleocr")]
    PaddleOcr,
    /// <summary>
    /// Custom/third-party OCR backend
    /// </summary>
    [JsonPropertyName("custom")]
    Custom,
}


/// <summary>
/// Custom JSON converter for <see cref="OcrBackendType"/> that respects explicit variant names.
/// </summary>
internal sealed class OcrBackendTypeJsonConverter : JsonConverter<OcrBackendType>
{
    public override OcrBackendType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var value = reader.GetString();
        return value switch
        {
            "tesseract" => OcrBackendType.Tesseract,
            "easyocr" => OcrBackendType.EasyOcr,
            "paddleocr" => OcrBackendType.PaddleOcr,
            "custom" => OcrBackendType.Custom,
            _ => throw new JsonException($"Unknown OcrBackendType value: {value}")
        };
    }

    public override void Write(Utf8JsonWriter writer, OcrBackendType value, JsonSerializerOptions options)
    {
        var str = value switch
        {
            OcrBackendType.Tesseract => "tesseract",
            OcrBackendType.EasyOcr => "easyocr",
            OcrBackendType.PaddleOcr => "paddleocr",
            OcrBackendType.Custom => "custom",
            _ => throw new JsonException($"Unknown OcrBackendType value: {value}")
        };
        writer.WriteStringValue(str);
    }
}
