// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:8a9c4cefc6c9d958a560f65e608bed80daf7d8735d9669110634565f533b964d
#nullable enable

using System;

namespace Kreuzberg;

public class OcrException : KreuzbergErrorException
{
    public OcrException(string message) : base(message) { }

    public OcrException(string message, Exception innerException) : base(message, innerException) { }
}
