// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:aa2b3852fb201832fb6551cb5d005097cdb35142c49612901a84711f8cead71f
#nullable enable

using System;

namespace Kreuzberg;

public class OtherException : KreuzbergErrorException
{
    public OtherException(string message) : base(message) { }

    public OtherException(string message, Exception innerException) : base(message, innerException) { }
}
