// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:617b9535f5b52ccb9477c09b2d8fc86afe20aa5a97970d42b0548baed969a96c
#nullable enable

using System;

namespace Kreuzberg;

public class ParsingException : KreuzbergErrorException
{
    public ParsingException(string message) : base(message) { }

    public ParsingException(string message, Exception innerException) : base(message, innerException) { }
}
