// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:5b8176056267b6fc362ed4d49d962fd2ae7c0990c6926602cfdb3dd3fa3c4ed5
#nullable enable

using System;

namespace Kreuzberg;

public class PluginException : KreuzbergErrorException
{
    public PluginException(string message) : base(message) { }

    public PluginException(string message, Exception innerException) : base(message, innerException) { }
}
