// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:4801c98b5ef509198f9a89712d2573696e9f9fd4d7941cd241beb02ccf37314e
#nullable enable

using System;

namespace Kreuzberg;

public class SecurityException : KreuzbergErrorException
{
    public SecurityException(string message) : base(message) { }

    public SecurityException(string message, Exception innerException) : base(message, innerException) { }
}
