// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:259828a08198128bf5fb5b09e332aa14906c5aea1dce104a61f893803d4ebe63
#nullable enable

using System;

namespace Kreuzberg;

public class SerializationException : KreuzbergErrorException
{
    public SerializationException(string message) : base(message) { }

    public SerializationException(string message, Exception innerException) : base(message, innerException) { }
}
