// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:fbf3cf9c5f9a616b986d3569a7dc613ae139fbe40b9bdf5cc1c4e1c63227c736
#nullable enable

using System;

namespace Kreuzberg;

public class TimeoutException : KreuzbergErrorException
{
    public TimeoutException(string message) : base(message) { }

    public TimeoutException(string message, Exception innerException) : base(message, innerException) { }
}
