// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:f1d34c869102233a059aa0b3b4e74957fce74fbc473686ae74a74c73e3a61097
#nullable enable

using System;

namespace Kreuzberg;

public class UnsupportedFormatException : KreuzbergErrorException
{
    public UnsupportedFormatException(string message) : base(message) { }

    public UnsupportedFormatException(string message, Exception innerException) : base(message, innerException) { }
}
