// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:3744301fcbb7ddf13e0c6ddf4be5192fb09554d721613ae4b5838271c3954aad
#nullable enable

using System;

namespace Kreuzberg;

public class ValidationException : KreuzbergErrorException
{
    public ValidationException(string message) : base(message) { }

    public ValidationException(string message, Exception innerException) : base(message, innerException) { }
}
