// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f2f4861f861d39bcd7cb264cc4fbcce8737e5d535770b3c5e5cdeab7338fbf0d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    include: ["tests/**/*.test.ts"],
    testTimeout: 30000,
    hookTimeout: 120000,
    teardownTimeout: 30000,
    setupFiles: ["./setup.ts"],
  },
});
