# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9222ea06ae09e8b1d08c8be6b3657cc6003a65698879631da696ff7bdf0556bd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: renderer_management

test_that("renderers_clear: Clear all renderers and verify list is empty", {
  invisible(clear_renderers())
  expect_true(TRUE)
})

test_that("renderers_list: List all registered renderers", {
  result <- list_renderers()
  expect_true(TRUE)
})
