# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4496c20a9f324939f1d031f31ee3ecc9a9a62441e29ec97101c3b6269a6c3f93
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: validator_management

test_that("validators_clear: Clear all validators and verify list is empty", {
  invisible(clear_validators())
  expect_true(TRUE)
})

test_that("validators_list: List all registered validators", {
  result <- list_validators()
  expect_true(TRUE)
})
