# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ba5090edebd0a76c632a6e3ebe7c31aba5c4745472dde27ab28c6a4e869f30ab
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: embed_extra

test_that("embed_texts_batch: Batch embed texts", {
  result <- embed_texts(texts = c("Hello", "World"), config = EmbeddingConfig$default())
  expect_true(TRUE)
})
