// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e5a1a357c0a2c6b124c7248d186d05e20a3666c2b4b1819ab37934249ef55a57
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

package dev.kreuzberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import dev.kreuzberg.Kreuzberg;
import dev.kreuzberg.ExtractionConfig;
import java.util.Optional;
import dev.kreuzberg.JsonUtil;

/** E2e tests for category: document_extractor_management. */
class DocumentExtractorManagementTest {

    @Test
    void testDocumentExtractorsClear() throws Exception {
        // Clear all document extractors and verify list is empty
        Kreuzberg.clearDocumentExtractors();

    }


    @Test
    void testExtractorsList() throws Exception {
        // List all registered document extractors
        var result = Kreuzberg.listDocumentExtractors();

    }

}
