// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ff92cd19df19364050bed8990520031f9255b265471c44f7880526eddb6fc609
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

package dev.kreuzberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import dev.kreuzberg.Kreuzberg;
import dev.kreuzberg.EmbeddingConfig;
import dev.kreuzberg.ExtractionConfig;
import java.util.Optional;
import dev.kreuzberg.JsonUtil;

/** E2e tests for category: embed_async_pending. */
class EmbedAsyncPendingTest {

    @Test
    void testEmbedTextsAsyncEmptyInput() throws Exception {
        // embed_texts_async: empty text list
        var result = Kreuzberg.embedTextsAsync(java.util.List.of(), EmbeddingConfig.builder().build());
assertEquals(0, result.size(), "expected exactly 0 elements");
    }


    @Test
    void testEmbedTextsAsyncHappy() throws Exception {
        // embed_texts_async: basic async embedding
        var result = Kreuzberg.embedTextsAsync(java.util.Arrays.asList(JsonUtil.fromJson("\"First\"", String.class), JsonUtil.fromJson("\"Second\"", String.class)), EmbeddingConfig.builder().build());
assertTrue(result.size() >= 2, "expected at least 2 elements");
    }


    @Test
    void testEmbedTextsAsyncPresetSwitch() throws Exception {
        // embed_texts_async: preset override
        var config = JsonUtil.fromJson("{\"embedding_model\":\"default\"}", EmbeddingConfig.class);

        var result = Kreuzberg.embedTextsAsync(java.util.Arrays.asList(JsonUtil.fromJson("\"Text\"", String.class)), config);

    }

}
