// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:845b123dac0f797d9e28c354f4fa4e41477c72fb80580feb91b7c602aa311e8f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

package dev.kreuzberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import dev.kreuzberg.Kreuzberg;
import dev.kreuzberg.ExtractionConfig;
import java.util.Optional;
import dev.kreuzberg.JsonUtil;

/** E2e tests for category: post_processor_management. */
class PostProcessorManagementTest {

    @Test
    void testPostProcessorsClear() throws Exception {
        // Clear all post-processors and verify list is empty
        Kreuzberg.clearPostProcessors();

    }


    @Test
    void testPostProcessorsList() throws Exception {
        // List all registered post-processors
        var result = Kreuzberg.listPostProcessors();

    }

}
