// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:65f544209e06c12cca7a0d03033691b6af01c6f8121407caf0270106fef7dc4f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

package dev.kreuzberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import dev.kreuzberg.Kreuzberg;
import dev.kreuzberg.ExtractionConfig;
import java.util.Optional;
import dev.kreuzberg.JsonUtil;

/** E2e tests for category: renderer_management. */
class RendererManagementTest {

    @Test
    void testRenderersClear() throws Exception {
        // Clear all renderers and verify list is empty
        Kreuzberg.clearRenderers();

    }


    @Test
    void testRenderersList() throws Exception {
        // List all registered renderers
        var result = Kreuzberg.listRenderers();

    }

}
