# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ec363fafb610ab3ef2943ecbc9c4b834d1734e0ae7c68d526b9fa54c5dce6d9f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

module Kreuzberg
  VERSION = '5.0.0.pre.rc.1'
end
