# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e2ea82d7ee5a6eb26c6a9a4570c446ced231f20c6026fe82d855b91ca6e2e85b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

module Kreuzberg
  VERSION = "5.0.0.pre.rc.1"
end
