# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d79e1d26d35b883a9b95d60f21be40fadb213ce0431938010a3c219ccbaa772f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

require_relative "kreuzberg/version"
require_relative "kreuzberg/native"

module Kreuzberg
  # Re-export all types and functions from native extension
end
