# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f957a0bb54fe8723a07a4e54be14d39239018cc18da42967aa2f6242917e3c87
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

require_relative 'kreuzberg/version'
require_relative 'kreuzberg/native'

module Kreuzberg
  # Re-export all types and functions from native extension
end
