// DO NOT EDIT - auto-generated by alef
// alef:hash:643697d286a5bc3c0882a4de9811087f8cf0a109c8da7b2cbaa838169f02b7d9
package dev.kreuzberg;

public class CacheException extends KreuzbergErrorException {
    /** Creates a new CacheException with the given message. */
    public CacheException(final String message) {
        super(message);
    }

    /** Creates a new CacheException with the given message and cause. */
    public CacheException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
