// DO NOT EDIT - auto-generated by alef
// alef:hash:28c02eedf1791e7971bb74fc5e0a4da39601864b88075c91b4bb44d3426fef6d
package dev.kreuzberg;

public class CancelledException extends KreuzbergErrorException {
    /** Creates a new CancelledException with the given message. */
    public CancelledException(final String message) {
        super(message);
    }

    /** Creates a new CancelledException with the given message and cause. */
    public CancelledException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
