// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:bb6133ee22433dc27fa220aa51acd1470cc7044b0098ae3463993fa752c6543b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import org.jspecify.annotations.Nullable;

/**
 * Configuration for email extraction.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = EmailConfig.Builder.class)
public record EmailConfig(@Nullable @JsonProperty("msg_fallback_codepage") Integer msgFallbackCodepage) {
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    @JsonPOJOBuilder(withPrefix = "with")
    public static final class Builder {

        @JsonProperty("msg_fallback_codepage")
private Integer msgFallbackCodepage = null;

        /** Sets the msgFallbackCodepage field. */
        @JsonProperty("msg_fallback_codepage")
        public Builder withMsgFallbackCodepage(final @Nullable int value) {
            this.msgFallbackCodepage = value;
            return this;
        }

        /** Builds the EmailConfig instance. */
        public EmailConfig build() {
            return new EmailConfig(
                msgFallbackCodepage
            );
        }
    }
    // CPD-ON
}
