// DO NOT EDIT - auto-generated by alef
// alef:hash:2b67025a95b1e0e317eacd2605301051bce72f120d3bc8c22270a9ab6b8c0e17
package dev.kreuzberg;

public class EmbeddingException extends KreuzbergErrorException {
    /** Creates a new EmbeddingException with the given message. */
    public EmbeddingException(final String message) {
        super(message);
    }

    /** Creates a new EmbeddingException with the given message and cause. */
    public EmbeddingException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
