// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:24c0d251e5f4d5f04b7b50484fc7c3f387de12237262c6acee4986b712f3510d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.Map;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Image metadata extracted from an image file.
 */
public record ExtractedImageMetadata(
    /**
     * Image width in pixels
     */
    int width,
    /**
     * Image height in pixels
     */
    int height,
    /**
     * Image format (e.g., "PNG", "JPEG")
     */
    String format,
    /**
     * EXIF data if available
     */
    @JsonProperty("exif_data") Map<String, String> exifData
) {
}
