// DO NOT EDIT - auto-generated by alef
// alef:hash:ce952a4d7e0071258c6c70e642eede9c31b4fd26734b008399d69759a48b08a0
package dev.kreuzberg;

public class ImageProcessingException extends KreuzbergErrorException {
    /** Creates a new ImageProcessingException with the given message. */
    public ImageProcessingException(final String message) {
        super(message);
    }

    /** Creates a new ImageProcessingException with the given message and cause. */
    public ImageProcessingException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
