// DO NOT EDIT - auto-generated by alef
// alef:hash:4cff6f7644f2ab31f711d89ebd7ee42f1f23a7b0ea23706848b45f6308c91fd0
package dev.kreuzberg;

public class IoException extends KreuzbergErrorException {
    /** Creates a new IoException with the given message. */
    public IoException(final String message) {
        super(message);
    }

    /** Creates a new IoException with the given message and cause. */
    public IoException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
