// DO NOT EDIT - auto-generated by alef
// alef:hash:8ea9d802e5e2bf31f68eb3774a73a3a9b83056b5134a4ba76a135c2bbcedde0d
package dev.kreuzberg;

public class LockPoisonedException extends KreuzbergErrorException {
    /** Creates a new LockPoisonedException with the given message. */
    public LockPoisonedException(final String message) {
        super(message);
    }

    /** Creates a new LockPoisonedException with the given message and cause. */
    public LockPoisonedException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
