// DO NOT EDIT - auto-generated by alef
// alef:hash:b064fd1912f51c88e5cc265e1b91c2501897e23b8c83d42514d54909e71878c4
package dev.kreuzberg;

public class MissingDependencyException extends KreuzbergErrorException {
    /** Creates a new MissingDependencyException with the given message. */
    public MissingDependencyException(final String message) {
        super(message);
    }

    /** Creates a new MissingDependencyException with the given message and cause. */
    public MissingDependencyException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
