// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8b96d55cbafe6b69fb2c027c7864c74d290eb74bb18dd66c7d86549937024815
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;

public record OcrCacheStats(
    @JsonProperty("total_files") long totalFiles,
    @JsonProperty("total_size_mb") double totalSizeMb
) {
}
