// DO NOT EDIT - auto-generated by alef
// alef:hash:beea0675c8f1f712b53b10cc13eaa3f2b8cab4aa9d0f1d691b35bedf148e86d6
package dev.kreuzberg;

public class OcrException extends KreuzbergErrorException {
    /** Creates a new OcrException with the given message. */
    public OcrException(final String message) {
        super(message);
    }

    /** Creates a new OcrException with the given message and cause. */
    public OcrException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
