// DO NOT EDIT - auto-generated by alef
// alef:hash:c86ffe577205d7fc6a38679373198a7447022c4dcc45bb1a35c4e4bb57a7fc41
package dev.kreuzberg;

public class OtherException extends KreuzbergErrorException {
    /** Creates a new OtherException with the given message. */
    public OtherException(final String message) {
        super(message);
    }

    /** Creates a new OtherException with the given message and cause. */
    public OtherException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
