// DO NOT EDIT - auto-generated by alef
// alef:hash:6c604443095d1fb164d0f48f387cbfa33e2c4a14a32ac8a5d28363cddbbd3d6d
package dev.kreuzberg;

public class ParsingException extends KreuzbergErrorException {
    /** Creates a new ParsingException with the given message. */
    public ParsingException(final String message) {
        super(message);
    }

    /** Creates a new ParsingException with the given message and cause. */
    public ParsingException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
