// DO NOT EDIT - auto-generated by alef
// alef:hash:1e5bbc1b1767b978173088330dd58b1d11555087104e293a6e6972d4eff1efe0
package dev.kreuzberg;

public class PluginException extends KreuzbergErrorException {
    /** Creates a new PluginException with the given message. */
    public PluginException(final String message) {
        super(message);
    }

    /** Creates a new PluginException with the given message and cause. */
    public PluginException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
