// DO NOT EDIT - auto-generated by alef
// alef:hash:4ca2dcf18975272d3bfcec1695498547419a44478074b8bfdc65ea750ab253c4
package dev.kreuzberg;

public class SecurityException extends KreuzbergErrorException {
    /** Creates a new SecurityException with the given message. */
    public SecurityException(final String message) {
        super(message);
    }

    /** Creates a new SecurityException with the given message and cause. */
    public SecurityException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
