// DO NOT EDIT - auto-generated by alef
// alef:hash:16ed2725d588feada11845088f91c5d78eb8beb926fce9815bc0a2b39f51d1bb
package dev.kreuzberg;

public class SerializationException extends KreuzbergErrorException {
    /** Creates a new SerializationException with the given message. */
    public SerializationException(final String message) {
        super(message);
    }

    /** Creates a new SerializationException with the given message and cause. */
    public SerializationException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
