// DO NOT EDIT - auto-generated by alef
// alef:hash:b0a76b5857cb9716092eb4a14dc08c1bd4d95d1d7313aded4f23b081765ea491
package dev.kreuzberg;

public class TimeoutException extends KreuzbergErrorException {
    /** Creates a new TimeoutException with the given message. */
    public TimeoutException(final String message) {
        super(message);
    }

    /** Creates a new TimeoutException with the given message and cause. */
    public TimeoutException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
