// DO NOT EDIT - auto-generated by alef
// alef:hash:727e3d3d2597a612d2e2e266cc3bda3e5d9d17440497a820c01645383cc2b1cb
package dev.kreuzberg;

public class UnsupportedFormatException extends KreuzbergErrorException {
    /** Creates a new UnsupportedFormatException with the given message. */
    public UnsupportedFormatException(final String message) {
        super(message);
    }

    /** Creates a new UnsupportedFormatException with the given message and cause. */
    public UnsupportedFormatException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
