// DO NOT EDIT - auto-generated by alef
// alef:hash:295840beac0287942b18cfef62c3c17dae7b001ac3e77734d50cccb9746fdf3d
package dev.kreuzberg;

public class ValidationException extends KreuzbergErrorException {
    /** Creates a new ValidationException with the given message. */
    public ValidationException(final String message) {
        super(message);
    }

    /** Creates a new ValidationException with the given message and cause. */
    public ValidationException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
