# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:23b9f8025d429ecce1f51dd3bbef3d0458f1ec42db3369602c39bdd27325086b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DbfFieldInfo do
  @moduledoc "dBASE field information."

  @typedoc "dBASE field information."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          field_type: String.t() | nil
        }

  defstruct name: nil,
            field_type: nil
end
