# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:59f8a595643a80607aab23e441303db56cf12d0f8e4e7f1f42e7577f38aade08
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DbfMetadata do
  @moduledoc "dBASE (DBF) file metadata."

  @typedoc "dBASE (DBF) file metadata."
  @type t :: %__MODULE__{
          record_count: non_neg_integer(),
          field_count: non_neg_integer(),
          fields: [map()]
        }

  defstruct record_count: 0,
            field_count: 0,
            fields: []

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
