# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cd07bb49d59edd386893de4a129f93b97211c3d832f8ffbba35e6ef3477ff51b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DjotLink do
  @moduledoc "Link element in Djot."

  @typedoc "Link element in Djot."
  @type t :: %__MODULE__{
          url: String.t() | nil,
          text: String.t() | nil,
          title: String.t() | nil,
          attributes: String.t() | nil
        }

  defstruct url: nil,
            text: nil,
            title: nil,
            attributes: nil
end
