# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f95504d8fcbd63251cf8dc8f8358beaf835c8cda0388be6bd0003c1a3f3de4c5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DocumentRelationship do
  @moduledoc "A resolved relationship between two nodes in the document tree."

  @typedoc "A resolved relationship between two nodes in the document tree."
  @type t :: %__MODULE__{
          source: non_neg_integer(),
          target: non_neg_integer(),
          kind: String.t() | nil
        }

  defstruct source: 0,
            target: 0,
            kind: :footnote_reference
end
