# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:078e70b20584aaee1fb297d3c1db04f9ded7b0d086ed9899ba34d0e60b418e38
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmailConfig do
  @moduledoc "Configuration for email extraction."

  @typedoc "Configuration for email extraction."
  @type t :: %__MODULE__{
          msg_fallback_codepage: non_neg_integer() | nil
        }

  defstruct msg_fallback_codepage: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
