# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:28a93136d3f1c4fbd9e6c8261f86de56a0b034350fe537f976e9deb08a94704a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmbeddingModelType do
  @moduledoc "Embedding model types supported by Kreuzberg."

  @typedoc "Embedding model types supported by Kreuzberg."
  @type t :: term()

  @typedoc "Use a preset model configuration (recommended)"
  @type preset :: %{type: :preset, name: String.t()}
  @typedoc "Use a custom ONNX model from HuggingFace"
  @type custom :: %{type: :custom, model_id: String.t(), dimensions: non_neg_integer()}
  @typedoc "Provider-hosted embedding model via liter-llm."
  @type llm :: %{type: :llm, llm: Kreuzberg.LlmConfig.t()}
  @typedoc "In-process embedding backend registered via the plugin system."
  @type plugin :: %{type: :plugin, name: String.t()}
end
