# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f29e31958e0fea2ddadc9c503f33b39ab277a22e6ffea6fc25937615ab327ed7
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ErrorMetadata do
  @moduledoc "Error metadata (for batch operations)."

  @typedoc "Error metadata (for batch operations)."
  @type t :: %__MODULE__{
          error_type: String.t() | nil,
          message: String.t() | nil
        }

  defstruct error_type: nil,
            message: nil
end
