# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:48d56afed25dde996feec77c5627be73c7e0648fce3434f2440b68bcedcc74f7
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ErrorMetadata do
  @moduledoc "Error metadata (for batch operations)."

  @typedoc "Error metadata (for batch operations)."
  @type t :: %__MODULE__{
          error_type: String.t() | nil,
          message: String.t() | nil
        }

  defstruct error_type: nil,
            message: nil
end
