# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a55bf2e63dc0ae7da60f6049f1e22fb50faacec64317ec6d405dc5553add1cc9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ExcelWorkbook do
  @moduledoc """
  Excel workbook representation.

  Contains all sheets from an Excel file (.xlsx, .xls, etc.) with
  extracted content and metadata.
  """

  @typedoc "Excel workbook representation."
  @type t :: %__MODULE__{
          sheets: [map()],
          metadata: map()
        }

  defstruct sheets: [],
            metadata: %{}
end
