# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7638dfa40fef4cd4c4a192c9a9a754c64cdf09993b331e89d5384c572b4aaece
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ExcelWorkbook do
  @moduledoc """
  Excel workbook representation.

  Contains all sheets from an Excel file (.xlsx, .xls, etc.) with
  extracted content and metadata.
  """

  @typedoc "Excel workbook representation."
  @type t :: %__MODULE__{
          sheets: [map()],
          metadata: map()
        }

  defstruct sheets: [],
            metadata: %{}
end
