# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c6398b94db71b78147fc54fb96e3e29cd4a15450469fb23403961757f883a059
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ExtractedImageMetadata do
  @moduledoc "Image metadata extracted from an image file."

  @typedoc "Image metadata extracted from an image file."
  @type t :: %__MODULE__{
          width: non_neg_integer(),
          height: non_neg_integer(),
          format: String.t() | nil,
          exif_data: map()
        }

  defstruct width: 0,
            height: 0,
            format: nil,
            exif_data: %{}
end
