# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:00de02fd050c8dfa201e8dc57f0c19cc106304a41dac1b9b6c49407f3a78c054
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.FictionBookMetadata do
  @moduledoc "FictionBook (FB2) metadata."

  @typedoc "FictionBook (FB2) metadata."
  @type t :: %__MODULE__{
          genres: [String.t()],
          sequences: [String.t()],
          annotation: String.t() | nil
        }

  defstruct genres: [],
            sequences: [],
            annotation: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
