# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5fb6e91e8a08f33c275d17a3bf77562ae4de30f6962b6c279b7178182b31e7da
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.Footnote do
  @moduledoc "Footnote in Djot."

  @typedoc "Footnote in Djot."
  @type t :: %__MODULE__{
          label: String.t() | nil,
          content: [map()]
        }

  defstruct label: nil,
            content: []
end
