# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:085fa58e7d03b794b5a3c1e52d50ab3a96ddc495297378c635977ed5a189eba8
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.HeadingContext do
  @moduledoc """
  Heading context for a chunk within a Markdown document.

  Contains the heading hierarchy from document root to this chunk's section.
  """

  @typedoc "Heading context for a chunk within a Markdown document."
  @type t :: %__MODULE__{
          headings: [map()]
        }

  defstruct headings: []
end
