# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0a85b7dab064e5585ea27ec1263fc95a6f1458e7fd277b4548f51533c9dca8e7
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.InlineElement do
  @moduledoc """
  Inline element within a block.

  Represents text with formatting, links, images, etc.
  """

  @typedoc "Inline element within a block."
  @type t :: %__MODULE__{
          element_type: String.t() | nil,
          content: String.t() | nil,
          attributes: String.t() | nil,
          metadata: map() | nil
        }

  defstruct element_type: :text,
            content: nil,
            attributes: nil,
            metadata: nil
end
