# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5be04bcb8b06525c8cb4c5d94f613008adc69baa335e0a662acb2507b2011c80
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.JatsMetadata do
  @moduledoc "JATS (Journal Article Tag Suite) metadata."

  @typedoc "JATS (Journal Article Tag Suite) metadata."
  @type t :: %__MODULE__{
          copyright: String.t() | nil,
          license: String.t() | nil,
          history_dates: map(),
          contributor_roles: [map()]
        }

  defstruct copyright: nil,
            license: nil,
            history_dates: %{},
            contributor_roles: []

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
