# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b53b458c083ae883b6ccf996c7994b5c3cb2e3770d98091d7fc8ad56e66b8cc9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.KeywordConfig do
  @moduledoc "Keyword extraction configuration."

  @typedoc "Keyword extraction configuration."
  @type t :: %__MODULE__{
          algorithm: String.t() | nil,
          max_keywords: non_neg_integer(),
          min_score: float(),
          ngram_range: [non_neg_integer()],
          language: String.t() | nil,
          yake_params: map() | nil,
          rake_params: map() | nil
        }

  defstruct algorithm: :yake,
            max_keywords: 10,
            min_score: 0,
            ngram_range: [],
            language: nil,
            yake_params: nil,
            rake_params: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
