# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ed9a79c711bca41a1d7a273f552e9614e79ded1ec66ef2f6dba897f655a04359
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.LanguageDetectionConfig do
  @moduledoc "Language detection configuration."

  @typedoc "Language detection configuration."
  @type t :: %__MODULE__{
          enabled: boolean(),
          min_confidence: float(),
          detect_multiple: boolean()
        }

  defstruct enabled: true,
            min_confidence: 0.8,
            detect_multiple: false

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
