# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:33281b12c37bf7ae7ae20d505ff5f8a685b8bc0e0b402a90e9e50d33f7aec95c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrCacheStats do
  @moduledoc false

  @type t :: %__MODULE__{
          total_files: non_neg_integer(),
          total_size_mb: float()
        }

  defstruct total_files: 0,
            total_size_mb: 0.0

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
