# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5e9883b9225d1eb0d552f89d82d73b49175785d2a20f5743c697f3651826e139
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrTableBoundingBox do
  @moduledoc "Bounding box for an OCR-detected table in pixel coordinates."

  @typedoc "Bounding box for an OCR-detected table in pixel coordinates."
  @type t :: %__MODULE__{
          left: non_neg_integer(),
          top: non_neg_integer(),
          right: non_neg_integer(),
          bottom: non_neg_integer()
        }

  defstruct left: 0,
            top: 0,
            right: 0,
            bottom: 0
end
