# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a8eec2e46d497ca5f25592c7e211f5656a302b530ee370cd7e9bef0085b73278
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrConfidence do
  @moduledoc """
  Confidence scores for an OCR element.

  Separates detection confidence (how confident that text exists at this location)
  from recognition confidence (how confident about the actual text content).
  """

  @typedoc "Confidence scores for an OCR element."
  @type t :: %__MODULE__{
          detection: float() | nil,
          recognition: float()
        }

  defstruct detection: nil,
            recognition: 0.0

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
