# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8f35bc058e79f3f2a969fe5464f8f1beb73bc7f5f58ab0044aa802bd65df11c4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrPipelineStage do
  @moduledoc "A single backend stage in the OCR pipeline."

  @typedoc "A single backend stage in the OCR pipeline."
  @type t :: %__MODULE__{
          backend: String.t() | nil,
          priority: non_neg_integer(),
          language: String.t() | nil,
          tesseract_config: map() | nil,
          paddle_ocr_config: String.t() | nil,
          vlm_config: map() | nil,
          backend_options: String.t() | nil
        }

  defstruct backend: nil,
            priority: 0,
            language: nil,
            tesseract_config: nil,
            paddle_ocr_config: nil,
            vlm_config: nil,
            backend_options: nil
end
