# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:453d853eeac11de02517cc0dc5557173ecb66727c8a94bde5a80675676b6c30d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PdfAnnotation do
  @moduledoc "A PDF annotation extracted from a document page."

  @typedoc "A PDF annotation extracted from a document page."
  @type t :: %__MODULE__{
          annotation_type: String.t() | nil,
          content: String.t() | nil,
          page_number: non_neg_integer(),
          bounding_box: String.t() | nil
        }

  defstruct annotation_type: :text,
            content: nil,
            page_number: 0,
            bounding_box: nil
end
