# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:29a83f5c98729f219aef8f171ff9f73c83f7165940adbd42e56638e1840c44d6
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ProcessingWarning do
  @moduledoc """
  A non-fatal warning from a processing pipeline stage.

  Captures errors from optional features that don't prevent extraction
  but may indicate degraded results.
  """

  @typedoc "A non-fatal warning from a processing pipeline stage."
  @type t :: %__MODULE__{
          source: String.t() | nil,
          message: String.t() | nil
        }

  defstruct source: nil,
            message: nil
end
