# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2dd763c7d9ec38071ee2a115619757751c72e64ade2b3eb596102a5dd1294f76
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ProcessingStage do
  @moduledoc """
  Processing stages for post-processors.

  Post-processors are executed in stage order (Early → Middle → Late).
  Use stages to control the order of post-processing operations.
  """

  @typedoc "Processing stages for post-processors."
  @type t :: :early | :middle | :late

  @early :early
  @middle :middle
  @late :late

  @doc "Early stage - foundational processing."
  @spec early() :: t()
  def early, do: @early
  @doc "Middle stage - content transformation."
  @spec middle() :: t()
  def middle, do: @middle
  @doc "Late stage - final enrichment."
  @spec late() :: t()
  def late, do: @late
end
