# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f1eb017adb679981e17973acfc5ef9dc5233f114d1d8b50cf33f39c6f8219b74
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PstMetadata do
  @moduledoc "Outlook PST archive metadata."

  @typedoc "Outlook PST archive metadata."
  @type t :: %__MODULE__{
          message_count: non_neg_integer()
        }

  defstruct message_count: 0

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
