# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d9b1ff3ed7d3263cd8967e038d92dba62f18755857d3ac567673ea0aac8aea76
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.RecognizedTable do
  @moduledoc """
  Pre-computed table markdown for a table detection region.

  Produced by the TATR-based table structure recognizer and surfaced as part of
  layout-aware OCR results.  The struct lives here (under `layout-types`, pure-Rust)
  so that consumers who do not enable `layout-detection` (ORT) can still reference
  the type in their own code.
  """

  @typedoc "Pre-computed table markdown for a table detection region."
  @type t :: %__MODULE__{
          detection_bbox: map(),
          cells: [[String.t()]],
          markdown: String.t() | nil
        }

  defstruct detection_bbox: nil,
            cells: [],
            markdown: nil
end
