# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:780aedf429e9cc5a50275b6d9e1c0c3a090afa48a1f3f42715656ef85490b8b5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ReductionLevel do
  @moduledoc false

  @type t :: :off | :light | :moderate | :aggressive | :maximum

  @off :off
  @light :light
  @moderate :moderate
  @aggressive :aggressive
  @maximum :maximum

  @spec off() :: t()
  def off, do: @off
  @spec light() :: t()
  def light, do: @light
  @spec moderate() :: t()
  def moderate, do: @moderate
  @spec aggressive() :: t()
  def aggressive, do: @aggressive
  @spec maximum() :: t()
  def maximum, do: @maximum
end
