# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:db2faaac96ef825cfc84573efc912c7387215966d0c83962843b3ed1d8c5d667
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.TableGrid do
  @moduledoc """
  Structured table grid with cell-level metadata.

  Stores row/column dimensions and a flat list of cells with position info.
  """

  @typedoc "Structured table grid with cell-level metadata."
  @type t :: %__MODULE__{
          rows: non_neg_integer(),
          cols: non_neg_integer(),
          cells: [map()]
        }

  defstruct rows: 0,
            cols: 0,
            cells: []

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
