# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8f7e9ee0d8403dc49fd33e2b0d08ebf10d8b3a7bd4f95024b4782b6867b134ae
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.Table do
  @moduledoc """
  Extracted table structure.

  Represents a table detected and extracted from a document (PDF, image, etc.).
  Tables are converted to both structured cell data and Markdown format.
  """

  @typedoc "Extracted table structure."
  @type t :: %__MODULE__{
          cells: [[String.t()]],
          markdown: String.t() | nil,
          page_number: non_neg_integer(),
          bounding_box: String.t() | nil
        }

  defstruct cells: [],
            markdown: nil,
            page_number: 0,
            bounding_box: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
