# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0006654695d8250bbd80c1b18f54af4229e1cdc5eedbb8724479556e91335ce1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.TokenReductionOptions do
  @moduledoc "Token reduction configuration."

  @typedoc "Token reduction configuration."
  @type t :: %__MODULE__{
          mode: String.t() | nil,
          preserve_important_words: boolean()
        }

  defstruct mode: nil,
            preserve_important_words: true

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
