# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d0deb6fcd94f6fc91deba77ad1d2750a436249f119e78e58753711f1ff6a07c2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef

#' @useDynLib kreuzberg, .registration = TRUE
NULL
