# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b1479d4d5ac2e43f0dde7ea0cb54d477a6d60d1cbaf221079d0d40edeb5b47b0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef

#' @useDynLib kreuzberg, .registration = TRUE
NULL
