// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:bfab4df668c775b278a4b36214f35fdf4ce5a325dbd21202a571b118e037c560
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

import { describe, expect, it } from "vitest";
import {
  extractFile,
  extractBytes,
  WasmExtractionConfig,
  WasmStructuredExtractionConfig,
  WasmTreeSitterProcessConfig,
  WasmPostProcessorConfig,
  WasmKeywordConfig,
  WasmSecurityLimits,
  WasmImagePreprocessingConfig,
  WasmImageExtractionConfig,
  WasmTokenReductionOptions,
  WasmPageConfig,
  WasmLayoutDetectionConfig,
  WasmYakeParams,
  WasmHierarchyConfig,
  WasmContentFilterConfig,
  WasmOcrQualityThresholds,
  WasmAccelerationConfig,
  WasmTesseractConfig,
  WasmEmbeddingConfig,
  WasmLlmConfig,
  WasmOcrPipelineConfig,
  WasmOcrElementConfig,
  WasmEmailConfig,
  WasmLanguageDetectionConfig,
  WasmPdfConfig,
  WasmOcrPipelineStage,
  WasmRakeParams,
  WasmTreeSitterConfig,
  WasmChunkingConfig,
  WasmHtmlOutputConfig,
  WasmOcrConfig,
} from "kreuzberg";
function _alefE2eText(value: unknown): string {
  return value == null ? "" : String(value);
}

function _alefE2eItemTexts(item: unknown): string[] {
  if (item == null || typeof item !== "object") {
    return [_alefE2eText(item)];
  }
  const record = item as Record<string, unknown>;
  const itemsText = Array.isArray(record.items) ? record.items.map(_alefE2eText).join(" ") : "";
  return [
    _alefE2eText(item),
    _alefE2eText(record.kind),
    _alefE2eText(record.name),
    _alefE2eText(record.source),
    _alefE2eText(record.alias),
    _alefE2eText(record.text),
    _alefE2eText(record.signature),
    itemsText,
  ];
}

describe("async", () => {
  it("async_extract_bytes_empty_mime: extract_bytes empty MIME async", async () => {
    await expect(async () => {
      const _content_content = await (await import("node:fs/promises")).readFile("text/plain.txt");
      await extractBytes(_content_content, "", undefined);
    }).rejects.toThrow();
  });
  it("async_extract_bytes_invalid_mime: extract_bytes unsupported MIME async", async () => {
    await expect(async () => {
      const _content_content = await (await import("node:fs/promises")).readFile("text/plain.txt");
      await extractBytes(_content_content, "application/x-nonexistent", undefined);
    }).rejects.toThrow();
  });
});
