# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5c016a2d8bc3eda98700736b11b40ceb8ad0701b379ffa5bd53b7d00ce59b4bc
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

require 'kreuzberg'
require 'json'
require 'spec_helper'

RSpec.describe 'document_extractor_management' do
  it 'document_extractors_clear: Clear all document extractors and verify list is empty' do
    Kreuzberg.clear_document_extractors()

  end

  it 'extractors_list: List all registered document extractors' do
    result = Kreuzberg.list_document_extractors()

    expect(result).not_to be_nil
  end
end
