// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ce9230ae679f87db72e1a44c007b47ad794dd1b7722761e4ad511e80061c3d62
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
// ignore_for_file: unused_local_variable

import 'package:test/test.dart';
import 'dart:io';
import 'package:kreuzberg/kreuzberg.dart';
import 'package:kreuzberg/src/kreuzberg_bridge_generated/frb_generated.dart' show RustLib;

// E2e tests for category: error

String _alefE2eText(Object? value) {
  if (value == null) return '';
  // Check if it's an enum by examining its toString representation.
  final str = value.toString();
  if (str.contains('.')) {
    // Enum.toString() returns 'EnumName.variantName'. Extract the variant name.
    final parts = str.split('.');
    if (parts.length == 2) {
      final variantName = parts[1];
      // Convert camelCase variant names to snake_case for serde compatibility.
      // E.g. 'toolCalls' -> 'tool_calls', 'stop' -> 'stop'.
      return _camelToSnake(variantName);
    }
  }
  return str;
}

String _camelToSnake(String camel) {
  final buffer = StringBuffer();
  for (int i = 0; i < camel.length; i++) {
    final char = camel[i];
    if (char.contains(RegExp(r'[A-Z]'))) {
      if (i > 0) buffer.write('_');
      buffer.write(char.toLowerCase());
    } else {
      buffer.write(char);
    }
  }
  return buffer.toString();
}

void main() {
  setUpAll(() async {
    await RustLib.init();
    final _testDocs = Platform.environment['FIXTURES_DIR'] ?? '../../test_documents';
    final _dir = Directory(_testDocs);
    if (_dir.existsSync()) Directory.current = _dir;
  });

  test('Graceful handling of empty bytes (should not error)', () async {
    final result = await KreuzbergBridge.extractBytesSync(File('text/empty.txt').readAsBytesSync(), mimeType: 'text/plain');
  });

  test('Error when extracting with empty MIME type', () async {
    await expectLater(KreuzbergBridge.extractBytesSync(File('text/plain.txt').readAsBytesSync(), mimeType: ''), throwsA(anything));
  });

  test('extract_bytes force+disable OCR', () async {
    await expectLater(KreuzbergBridge.extractBytesSync(File('text/fake_text.txt').readAsBytesSync(), mimeType: 'text/plain', ExtractionConfig(useCache: true, enableQualityProcessing: true, forceOcr: true, disableOcr: true, resultFormat: ResultFormat.unified, outputFormat: OutputFormat.plain(), includeDocumentStructure: false, useLayoutForMarkdown: false, maxArchiveDepth: 3)), throwsA(anything));
  });

  test('Error when extracting with invalid MIME type format', () async {
    await expectLater(KreuzbergBridge.extractBytesSync(File('text/plain.txt').readAsBytesSync(), mimeType: 'not-a-mime'), throwsA(anything));
  });

  test('Error when extracting with unsupported MIME type', () async {
    await expectLater(KreuzbergBridge.extractBytesSync(File('text/plain.txt').readAsBytesSync(), mimeType: 'application/x-nonexistent'), throwsA(anything));
  });

}
