// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c2bd09b3fa660836f07b4186e07c7d0a9545f434c1bfdd6ea099f9d488e883f9
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

// E2e tests for category: document_extractor_management
package e2e_test

import (
	"testing"

	kreuzberg "github.com/kreuzberg-dev/kreuzberg/v5"
)

func Test_DocumentExtractorsClear(t *testing.T) {
	// Clear all document extractors and verify list is empty
	_ = kreuzberg.ClearDocumentExtractors()
}

func Test_ExtractorsList(t *testing.T) {
	// List all registered document extractors
	_, err := kreuzberg.ListDocumentExtractors()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
