// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b286e56628742d8fef5f5abb130260ad9169ec4c9830d2c5c8323d430e17ac7b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

// E2e tests for category: embed_extra
package e2e_test

import (
	"encoding/json"
	"testing"

	kreuzberg "github.com/kreuzberg-dev/kreuzberg/v5"
)

func Test_EmbedTextsBatch(t *testing.T) {
	// Batch embed texts
	var texts []string
	if err := json.Unmarshal([]byte(`["hello","world"]`), &texts); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	_, err := kreuzberg.EmbedTexts(texts, kreuzberg.EmbeddingConfig{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
