// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:fe0ad383f201c259936bf83e9d79bcccb9171831d36294901138443590a7a3ac
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

// E2e tests for category: ocr_backend_management
package e2e_test

import (
	"testing"

	kreuzberg "github.com/kreuzberg-dev/kreuzberg/v5"
)

func Test_OcrBackendsClear(t *testing.T) {
	// Clear all OCR backends and verify list is empty
	_ = kreuzberg.ClearOcrBackends()
}

func Test_OcrBackendsList(t *testing.T) {
	// List all registered OCR backends
	_, err := kreuzberg.ListOcrBackends()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
