// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:107acb1ea6da599b228a6cd10ef6c1e37b7c624ea26903ece446e35c8ecad2bd
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import kotlinx.coroutines.runBlocking
import dev.kreuzberg.Kreuzberg

/** E2e tests for category: ocr_backend_management. */
class OcrBackendManagementTest {
    @Test
    fun testOcrBackendsList() = runBlocking {
        // List all registered OCR backends
        val result = Kreuzberg.listOcrBackends()
    }

}
