// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c69e91ed0796d01e832e4c581bb4ea8ca875afdf0cec41e6edfcade269c19995
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import kotlinx.coroutines.runBlocking
import dev.kreuzberg.Kreuzberg

/** E2e tests for category: post_processor_management. */
class PostProcessorManagementTest {
    @Test
    fun testPostProcessorsList() = runBlocking {
        // List all registered post-processors
        val result = Kreuzberg.listPostProcessors()
    }

}
